name: "commercial_app"
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_nav_bar: ^5.0.6
  path: ^1.9.0
  image: ^4.1.7
  flutter_typeahead: ^4.8.0
  http: ^1.2.1
  substring_highlight: ^1.0.33
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  get_it: ^7.7.0
  flutter_lints: ^4.0.0
  connectivity_plus: ^3.0.2
  pdf: ^3.11.2
  nested: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/evi_logo.png
    - assets/images/small_divider.png
    - assets/images/divider.png
    - assets/images/document_0591_R.png
    - assets/images/document_1951_V.png
    - assets/images/document_0590_R.png
    - assets/images/erik_diplom.png
    - assets/images/viktor_diplom.png
    - assets/images/erik_assertment.png
    - assets/images/viktor_assertment.png
    - assets/images/ooo_document.png
    - assets/images/qr-code.png
    - assets/images_for_readme/evi_1.png
    - assets/images_for_readme/evi_3.png
    - assets/images_for_readme/evi_5.png
    - assets/images_for_readme/evi_6.png
    - assets/images_for_readme/evi_7.png
    - assets/images_for_readme/evi_8.png
    - assets/images_for_readme/evi_9.png
    - assets/images_for_readme/evi_10.png
    - assets/fonts/
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura-pt-book.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
        - asset: assets/fonts/Arial-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arial-Italic.ttf
          style: italic

flutter_intl:
  enabled: true
