name: "commercial_app"
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_nav_bar: ^5.0.6
  path: ^1.9.0
  docx_template:
    path: /Users/nikitaermolaev/StudioProjects/commercial_app/docx_template
  image: ^4.1.7
  flutter_typeahead: ^4.8.0
  http: ^1.2.1
  substring_highlight: ^1.0.33
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  get_it: ^7.7.0
  flutter_lints: ^4.0.0
  connectivity_plus: ^3.0.2
  nested: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/templates/shablon_akta.docx
    - assets/gif/gifka.gif
    - assets/fonts/
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura-pt-book.ttf

flutter_intl:
  enabled: true
