// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjcZ3h7EF1gcbRQpFmLeLffx1rOT4y7mY',
    appId: '1:714673208016:web:b23058e2c657bad681bcd5',
    messagingSenderId: '714673208016',
    projectId: 'comercialapp-beed8',
    authDomain: 'comercialapp-beed8.firebaseapp.com',
    storageBucket: 'comercialapp-beed8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEiOvrmrHZR1mdMMsaTYGPao6-TABix3s',
    appId: '1:714673208016:android:717ed2026af05ec081bcd5',
    messagingSenderId: '714673208016',
    projectId: 'comercialapp-beed8',
    storageBucket: 'comercialapp-beed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIumc14TaDOO4EVQT6yM1AZdA6QmdaDOc',
    appId: '1:714673208016:ios:f51e86f299bebbf081bcd5',
    messagingSenderId: '714673208016',
    projectId: 'comercialapp-beed8',
    storageBucket: 'comercialapp-beed8.appspot.com',
    iosBundleId: 'com.nyermol.commercialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIumc14TaDOO4EVQT6yM1AZdA6QmdaDOc',
    appId: '1:714673208016:ios:fe2df5f823893b7581bcd5',
    messagingSenderId: '714673208016',
    projectId: 'comercialapp-beed8',
    storageBucket: 'comercialapp-beed8.appspot.com',
    iosBundleId: 'com.example.commercialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjcZ3h7EF1gcbRQpFmLeLffx1rOT4y7mY',
    appId: '1:714673208016:web:0ab38b9c8e0a520781bcd5',
    messagingSenderId: '714673208016',
    projectId: 'comercialapp-beed8',
    authDomain: 'comercialapp-beed8.firebaseapp.com',
    storageBucket: 'comercialapp-beed8.appspot.com',
  );
}
